#pragma once
#define WINDOW_CLASS_NAME	L"BLASTER_MASTER GAME"
#define MAIN_WINDOW_TITLE	L"AREA 2"
#define SCREEN_FILE_PATH	L"screen_manager\\main.txt"


#define BACKGROUND_COLOR D3DCOLOR_XRGB(255, 255, 200)
#define SCREEN_WIDTH 250
#define SCREEN_HEIGHT 250

#define MAX_FRAME_RATE 120

#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6

#define OBJECT_TYPE_JASON	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_INTRO	4
#define OBJECT_TYPE_BULLET	6
#define OBJECT_TYPE_ITEMS	20
#define OBJECT_TYPE_WORMS	9
#define OBJECT_TYPE_PORTAL	50
#define OBJECT_TYPE_SOPHIA	7
#define OBJECT_TYPE_TRAP	8

#define OBJECT_TYPE_DOMES	10
#define OBJECT_TYPE_JUMPERS	11
#define OBJECT_TYPE_INSECT	12
#define OBJECT_TYPE_ORBS	13
#define OBJECT_TYPE_FLOATERS 14


#define MAX_SCENE_LINE 1024